### ISSUE TITLE
Can't CopyBlock from CAL file to Detector

### ISSUE THREAD

**Issue by bdrum** [regata-jinr/Core#55]
I have to upload calibration files to detector, but I can't because of unhandled exception:

~~~csharp
            DeviceAccess d = null;
            DataAccess effFile = null;

            try
            {
                effFile = new DataAccess();
                effFile.Open(@"C:\GENIE2K\CALFILES\Efficiency\D1\D1-eff-2,5.CAL");

                d = new DeviceAccess();
                d.Connect("D1");
                // d.Param[CanberraDeviceAccessLib.ParamCodes.CAM_F_SQUANTERR] = 10;
                // d.Param[CanberraDeviceAccessLib.ParamCodes.CAM_F_SSYSTERR] = 20;
                // d.Param[CanberraDeviceAccessLib.ParamCodes.CAM_F_SSYSTERR] = 30;
                // d.Param[CanberraDeviceAccessLib.ParamCodes.CAM_T_SGEOMTRY] = "2.5";
                effFile.CopyBlock(d, CanberraDataAccessLib.ClassCodes.CAM_CLS_GEOM);
                effFile.Close();

            }
            finally
            {
                d?.Disconnect();
                if (effFile != null && effFile.IsOpen)
                    effFile.Close();
            }

~~~

Returns 

~~~
Unhandled exception. System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (0x80010105 (RPC_E_SERVERFAULT))
   at CanberraDataAccessLib.DataAccessClass.CopyBlock(Object Destination, ClassCodes lClass, ParamCodes lParam)
   at WorkFlowCore.Program.Main(String[] args) in D:\GoogleDrive\Projects\dotnet\playground\TestCanberraLibs\Program.cs:line 35
~~~

**Comment by bdrum** [comment]
There is an idea that the reason of this behavior is inspector version of genie on my laptop and absent of special usb key.

**Comment by bdrum** [comment]
It doesn't work with version 3.4.1_rev02 (Nov 2016)

Everything is fine with version 3.4.0.2877 (Mar 2015)
